[package]
name = "mrf-policy"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sonic-rs = "0.3.13"
once_cell = "1.20.2"
regex = "1.11.0"
